// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdaahplneuvxlshkoltj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkYWFocGxuZXV2eGxzaGtvbHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MDM4MDAsImV4cCI6MjA2Nzk3OTgwMH0.krLxatuHXLwvyAlOloP-ijobIyPXLWnadyhRa7COd5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});